root: true

extends: 
  - pegasus
  - pegasus/node

plugins:
  - angular
  
overrides:
  - files: '!src/*'
    rules:
      no-console: off
  
globals:
  angular: true

env:
  jasmine: true
  angular/mocks: true
