root: true

extends: 
  - airbnb-base

plugins:
  - angular
  
rules:
  import/no-extraneous-dependencies: off
  no-console: off
  
globals:
  angular: true

env:
  jasmine: true
  angular/mocks: true
